### ISSUE TITLE
persistence (a la memdb?)

### ISSUE THREAD

**Issue by karissa** [mafintosh/random-access-memory#1]
When using this with Hyperdrive, you can't read a file without getting an `improper length` message. Hyperdrive calls the `.close` method after the write is finished and the data gets deleted. 

Is this expected behavior?

**Comment by mafintosh** [comment]
2.0.0 does not clear the buffer on close

**Comment by mykola-vrmchk** [comment]
Does 4.1.0 clear the buffer on close?
